### ISSUE TITLE
Pressing the "Purchase Quickbuy" hotkey too fast will remove the item from Quickbuy.

### ISSUE THREAD

**Issue by AzimsTech** [jeffhill/Dota2#203]
### Description

As you can see, the last item in the Quickbuy disappears even if you don't have enough money to buy it. 

### Example Match ID (and possibly Timestamp)

This issue can be replicated inside online matchmaking and the custom lobby. 

### Screenshots

![gif](https://i.imgur.com/MVTEtgu.gif)

**Comment by NMOTH** [comment]
see where? you haven't provided any match id's or screen recordings. 
please replicate it and add recording to this post.

**Comment by ritvikgautam** [comment]
Happens even if you right click on the first item.

Taking the above dragon lance as an example, if you spam right click on the first item slot, and only have gold for 2 items, it will remove all 3 items from the quick buy but only buy 2 items.

**Comment by AzimsTech** [comment]
@Peasant255 Can confirm. 

![dota2_oDtsGMaYVs](https://user-images.githubusercontent.com/12103851/171877132-54e6a45d-6e4c-47e4-b752-e09fb604e30a.gif)

**Comment by Soong45** [comment]
Suspect I just encountered this issue in a game.
dota2://matchid=6604305078&matchtime=1181

**Comment by aetimmes** [comment]
I bind "purchase quick buy item" to mouse scroll wheel down and encounter this issue constantly.

**Comment by Aphotic** [comment]
Gorgc had this issue on stream & he malded over it:
https://clips.twitch.tv/BillowingResourcefulCroissantPMSTwin-fQ4YMExirDuAKZbF

**Comment by jeffhill** [comment]
This should be fixed in the next hotfix. I made changes to a bunch of the Quickbuy prediction code, and also changed the "cash register" noise to trigger server-side once it's confirmed you purchased the item. This may result in the sound being delayed relative to when you hear it right now, but on the other hand, it only triggers when you really, truly did buy the item.

Sorry, Gorgc!

**Comment by AzimsTech** [comment]
@jeffhill I'm still having issues in turbo match today.
![dota2_Fcw8U8onDY](https://user-images.githubusercontent.com/12103851/173744718-990fc484-83ca-40c6-b90a-7c8def079791.gif)
.

**Comment by Turmfalke2** [comment]
@jeffhill can you please reopen the issue? The quick buy is more broken than ever. 
Match id: 6621393887  ~1:30 into the game.
I started the game with 2 gauntlets of strength and queued up 2 bracers and phase boots. At ~1:30 I then bought the circlet and one bracer recipe in base using the courier and the game decided to put a new gauntlet of strength into my quick buy.


https://user-images.githubusercontent.com/5174562/174189002-cbbdbb3c-7707-47c1-8179-717c88891089.mp4


It happens again at ~2:50 when it duplicates the circlet in my quick buy.

**Comment by Aphotic** [comment]
> It happens again at ~2:50 when it duplicates the circlet in my quick buy.

yeah happened in my game too:
match id: 6621126031
i was almost ended up with 4 nulls on my KotL mid wanted to only buy 2!
i feel SHIFT+CTRL  is responsible, where you add more than one item to the shopping list?
min 2 of the game if you wanna watch jeff

**Comment by AzimsTech** [comment]
Blademail recipe just disappear from the quickbuy.  
Match ID: **6628568150** @ 10:20

https://user-images.githubusercontent.com/12103851/174884377-1f9c66fd-fd0f-450e-9044-992aae60e802.mp4

**Comment by Aphotic** [comment]
https://old.reddit.com/r/DotA2/comments/zbmhx7/how_is_quickbuy_still_broken_it_has_been_nearly/
seems to be occurring again ... 

also adding:     
"There is a quickbuy bug with buying 2 bracers/wraithband/ null talisman too where when the first bracer is complete, and if you have 1 component for the second bracer, it will readd the whole bracer to quickbuy (ideally it should be the remaining components)"

**Comment by Aphotic** [comment]
> This should be fixed in the next hotfix.
> Sorry, Gorgc!

https://old.reddit.com/r/DotA2/comments/zbmhx7/how_is_quickbuy_still_broken_it_has_been_nearly/
seems to be occurring again ... 

also adding:     
"There is a quickbuy bug with buying 2 bracers/wraithband/ null talisman too where when the first bracer is complete, and if you have 1 component for the second bracer, it will readd the whole bracer to quickbuy (ideally it should be the remaining components)"

**Comment by AzimsTech** [comment]
@Aphotic they never really fixed it.

**Comment by BassJMagan** [comment]
Can confirm this happens a lot. Feels server-side related, but shouldn't happen at all. an item should only be bought a single time per quickbuy press and it should remove that entry from the list so you can hit the button fast in succession if about to die.
