### ISSUE TITLE
Some abilities deal damage through BKB if reflected by Lotus Orb

### ISSUE THREAD

**Issue by wersonit** [jeffhill/Dota2#274]
### Ability name

Lightning Storm, Lotus Orb, Dagon, Ether Shock, Laguna Blade

### Description

Some certain abilities deal damage through BKB if they were reflected by Lotus Orb. 
It doesn't work for Finger of Death anymore, but it does work for every other ability in the list, and Dagon too.
https://www.reddit.com/r/DotA2/comments/l0vgvi/some_targeted_spells_pierce_bkb_if_reflected_by/
https://www.reddit.com/r/TrueDoTA2/comments/id0guk/inconsistent_interactions_between_bkb_and_lotus/
This video is quite old, but I did check it right now and it's still bugged.

### Example Match ID (and possibly Timestamp)

-

**Comment by nickwong1** [comment]
#272 is part of this. You should close the previous one and have everything here!

This actually also affects Soulbind since it is also based on Spell Reflection.
The wiki on Soulbind has a [section](https://dota2.fandom.com/wiki/Grimstroke#Soulbind) for this as well.

**Comment by wersonit** [comment]
Makes sense

**Comment by Chairraider** [comment]
Here is a more detailed list of spells affected by this bug, finger was fixed in the meantime but many of those spells still pierce immunity when reflected: [https://dev.dota2.com/forum/bugs/gameplay-bugs/269640-spell-reflection-causes-non-piercing-spells-to-pierce-spell-immunity](url)

Missing seem to be Sunder, pulverize, Reaper Scythe and mana void aswell.

**Comment by shubhrathi** [comment]
> Here is a more detailed list of spells affected by this bug, finger was fixed in the meantime but many of those spells still pierce immunity when reflected: [https://dev.dota2.com/forum/bugs/gameplay-bugs/269640-spell-reflection-causes-non-piercing-spells-to-pierce-spell-immunity](url)
> 
> Missing seem to be Sunder, pulverize, Reaper Scythe and mana void aswell.

They fixed Pulverize getting cancelled by echoshell if Primal have active BKB though (see attached video). Its time as well they fix for TB sunder and Lina (non aghs) laguna as well.

Pulverize now correctly goes through echo shell when Primal beast BKB is active

https://user-images.githubusercontent.com/12682588/171972023-5e98211a-ca25-4313-935f-0df9f1e80b58.mp4


Lina (non aghs) laguna and TB sunder still need a fix 

https://user-images.githubusercontent.com/12682588/171972135-fa67ae39-0ced-480f-ad30-77f7efc5b519.mp4


https://user-images.githubusercontent.com/12682588/171972281-064eca38-ddcb-4d9f-bb6d-89ef2efb834c.mp4

**Comment by alex-baltz** [comment]
Up for this. This bug almost cost me a game. Tried it on demo. This bug is still around.

![image](https://user-images.githubusercontent.com/21119173/215343317-e60fb69e-eaeb-4632-8c9b-6cac5fdca17c.png)

**Comment by wersonit** [comment]
> Up for this. This bug almost cost me a game. Tried it on demo. This bug is still around.
> 
> ![image](https://user-images.githubusercontent.com/21119173/215343317-e60fb69e-eaeb-4632-8c9b-6cac5fdca17c.png)

I feel like this will never get fixed. More than half a year passed and nothing happened.
