### ISSUE TITLE
Cosmetic: drow ranger arcana with silent wake

### ISSUE THREAD

**Issue by Kenjiynwa** [jeffhill/Dota2#29]
A lot of people says it’s a feature but it destroys the cape. No cape from silent wake is seen when equipped with arcana

**Comment by shiverisbjorn** [comment]
While it is funny to mess with people that bought hundred dollar item I do think it should be fixed

**Comment by Astiberon** [comment]
A possible solution to this problem is to make two switchable styles: with and without a cape.

**Comment by c1fr1** [comment]
Issue persists with all variants of the silent wake (crimson witness + golden + regular). The main piece of the arcana (the weapon) causes the issue.

**Comment by PikaChokeMe** [comment]
This issue never used to exist. It looked a little weird with the arcana as you could get a kind of double cape effect 
![double cape](https://user-images.githubusercontent.com/5521574/173705709-e0954626-ba01-4a13-b797-8874fc54c1a6.png)

but I'd argue there was no reason to go from this:
![Cape Present](https://user-images.githubusercontent.com/5521574/173705734-1b207bcf-ff8f-4005-937a-4dc5d7610813.png)

to this:
![Cape Gone](https://user-images.githubusercontent.com/5521574/173705747-d012e80f-a5b9-491f-acf6-021dfe4b9ca2.png)

**Comment by c1fr1** [comment]
> This issue never used to exist. It looked a little weird with the arcana as you could get a kind of double cape effect ![double cape](https://user-images.githubusercontent.com/5521574/173705709-e0954626-ba01-4a13-b797-8874fc54c1a6.png)

you can still get this double cape effect by equipping the shoulder piece of the arcana, silent wake, and any weapon that isn't the arcana since it is the arcana weapon that disables the cape from silent wake.
![double cape latest patch](https://user-images.githubusercontent.com/24968794/174268653-8c118d7c-88b7-4651-958e-4cf1dabc1962.png)

**Comment by PikaChokeMe** [comment]
I'd argue this is worse since this means it visually fixes nothing and only hides the cape lol

**Comment by Sheodar** [comment]
Still no progress (just comment for save issues)

**Comment by PikaChokeMe** [comment]
I checked this the other day, and sadly it's still broken. It doesn't look too bad with one of the quivers in particular. This repo is also growing more important issues by the day. Sadly it will probably stay broken for quite a while.

**Comment by Sheodar** [comment]
@PikaChokeMe it is important too, I think it's fair to ask to fix something that players paid a few hundred $ for and that WORKED before they started touching it.

**Comment by sean99556** [comment]
I completely understand the frustration here. My friends, some other people and I have reported a cosmetic bug in 2018 yet it is still not fixed. I just don't understand why they treat items paid by users less important than other bugs. They should really dedicated economy team to fix all the cosmetic bugs
