### ISSUE TITLE
7.31d Introduced Micro Stutters All Game

### ISSUE THREAD

**Issue by eshin087** [jeffhill/Dota2#915]
### Description

The latest patch introduced micro stutters throughout my game. Others on reddit are also reporting this.  It happens throughout the whole game. Played 6 games and it was in every game. Introducing more summons and illusions causes it to get worse. Doesn't seem to be a FPS issue as its a constant 130+.

Please let me know if you need more information.

-Intel® Core™ i7-10700K (3.8 GHz)
-NVIDIA® GeForce RTX™ 3090 (24 GB GDDR6X)
-Kingston HyperX® DDR4-3200 XMP SDRAM (32 GB)
-WD Black 1 TB PCIe® NVMe™ TLC M.2 SSD
-Windows 10

[](https://www.reddit.com/r/DotA2/comments/v86cld/micro_stutter_after_the_recent_update/)

**Comment by FazyDota** [comment]
I recall JeffHill mentioning how this diagnostic tool [](https://github.com/google/UIforETW) is incredibly helpful to devs for debugging these kind of issues. I am not hundred percent sure it is relevant here and do not have Dota 2 on this machine, but maybe someone else could try.

**Comment by Misezicedark** [comment]
The same applies for Mac M1 (Max). In the first game I played I have also seen that when you usually cast a spell (or a spell is casted) for the first time, the game will freeze. The problem is that this keeps repeating. This can easily be reproduced in demo, though due to heroes and multiple assets the issue is more prevalent in a regular game.

Thank you a lot Jeff and all the devs for this tracker and for all the hard work. It's good to have a place where to come and report an issue like this whenever it happens.

Screenshots

https://www.icloud.com/iclouddrive/014Lx6LLB332RbJ5e8zGooe5g#IMG_5857 - it's a video but it's too big to attach it here

**Comment by hallsteinx** [comment]
> If you are using the Vulkan graphics API then you will get stutter as the game does some pre-rendering or something like that, but it should only happen once as the results are cached. I wonder if the patch removed/reset the cache, or parts of it?

I won't speak on OP's behalf, but Nvidia GPU users tend to steer away from Vulkan for performance reasons. I'm using DX11.
For what it's worth, the kind of stuttering I am experiencing, which is presumably what the others are experiencing also is not the type of stuttering observed when caching in Vulkan. And that specific type of stuttering tends to go away once the cache is built, which is a one-time occurrence.

**Comment by Misezicedark** [comment]
For Mac users Vulkan is the option. I will test if it’s the caching tho’. It may be this but it feels like this plus more.

**Comment by daeayang** [comment]
I'm having the same issue. The last match I played where I didn't have this issue was 6/5 at 10AM. Since the patch, all 3 games I've played have had lag/stutters throughout the entire game. I've always had the game on "best looking" option for video settings without any issues. I tried decreasing the slider to "fastest" and it did not help at all.

**Comment by tick373** [comment]
I'm having stutters throughout every game of dota since the patch, additionally i seem to get BONUS stutters when global ults are used.... NEVER had issues before patch.

Operating System
	Windows 10 Home 64-bit
CPU
	Intel Core i7 @ 3.60GHz
	Coffee Lake 14nm Technology
RAM
	32.0GB
Motherboard
	Gigabyte Technology Co. Ltd. Z390 AORUS PRO WIFI-CF (U3E1)
	%1 Chipset
Graphics
	ROG PG259QN (1920x1080@360Hz)
	M2A1R-H (1920x1080@60Hz)
	4095MB NVIDIA GeForce RTX 2080 SUPER (MSI)	45 °C
Storage
	1863GB Samsung SSD 980 PRO 2TB (Unknown (SSD))
	931GB Samsung SSD 970 EVO Plus 1TB (Unknown (SSD))
Optical Drives
	No optical disk drives detected
Audio
	NVIDIA Virtual Audio Device (Wave Extensible) (WDM)

**Comment by Seitei** [comment]
Same here. Never had issues before, this seems to be a new development.

**Comment by Zedris** [comment]
same having micro stutters/lag i have 22 ping. latest nvidia drivers didnt have this issue before directx11. 2080 ti 9th gen i7 cpu. super weird

**Comment by sMc-cMs** [comment]
Played 3 games last night. Had lag/stutters in all 3 games. Didn't have these issues prior to the patch. 

System: 

i9-10900KF 
3090
32 MB Ram, CL16 at 4000mhz 
Windows 10

**Comment by codeMatt** [comment]
Played a few games today and noticed it immediately (also played last night before patch with no issues)

Specs:
AMD Ryzen 9 5900X 
Nvidia geforce RTX 3070
unsure of ram build but its 32gb
gfx driver: DX11

I also noticed larger stutters at random times (potentially global spells with AA), and I seemed to run into teammates far more, the teammate even said his hero model was far from mine while I'm watching my hero recalculate paths to get around him.

**Comment by jeffhill** [comment]
If someone could collect an ETL file using UI for ETW (https://github.com/google/UIforETW/releases) during the micro-stutters and share that, it would be incredibly helpful. An ETL file is basically a whole-machine process trace for where the time is going and the annoying micro-stutters will announce themselves on the graph (along with a reference to the code responsible).

Thank you!

**Comment by md97x** [comment]
@jeffhill Here's also a comment I made earlier on a similar issue: https://github.com/jeffhill/Dota2/issues/946#issuecomment-1151179927

Sharing because I think the console output could help.

**Comment by jeffhill** [comment]
Thank you, @md97x! Sadly, that message just means the networking code has detected that *something, somewhere* is being slow, it doesn't really point to where the problem is (like an ETL would).

**Comment by Misezicedark** [comment]
Regarding the Mac (M1 Max), I suppose to a degree is related to the Vulkan cache, but everytime a neutral item dropped, the animation of the item dropped on the ground stuttered very badly.

@jeffhill is there an option to collect the ETL file on a Mac?

**Comment by Turmfalke2** [comment]
feels like the rendering pipeline stalls every time it has to build a new shader. I guess the update nuked the shaker cache? Been spectating a few games and the performance is gradually recovering.

**Comment by vishnyo** [comment]
@jeffhill I wish to help. But dont know how to use this util ` ETL file using UI for ETW`. I can share access to my machine if it can help you.

**Comment by pontuslaestadius** [comment]
@jeffhill 
Even when browsing heroes, the UI studders and lags using Vulcan. Here is an ETL if it helps.
https://www.mediafire.com/file/29cr4f331r7t5d8/2022-06-09_20-08-44_pontu.etl/file

**Comment by teddybee-r** [comment]
I've had issues on Vulkan Linux for ages. This got fixed **before** the update for me. No issues now

POP_OS 20.04
Ryzen 2600, GTX 1080

Previous issues:
Game freezing on every Hero first render in the menu. 
Game freezing post game for 1-2min!
with Pre-shader-cache enabled

**Comment by TheRealWitblitz** [comment]
I had this exact same issue, but even before the patch. The game was fine up until about a week ago I started to notice some extreme micro stutters. Some people said it might be a Steam update? It's just horrible at the moment.

_**command line:**_ 
-novid -map dota -high -dx11 +fps_max 60 +exec autoexec

**_autoexec:_**
engine_no_focus_sleep 0
cl_forcepreload 1
sv_forcepreload 1

**Comment by Fnrod** [comment]
Same here, only heroes and creeps are stuttering

**Comment by AmanovAkbar** [comment]
Same for me, in my last game not only me, but also my teammates and opposing team mentioned those stutters, what is interesting, there was no fps drops or high ping. It was a perfect internet connection and my comfortable 120 fps, but the game freezing pretty hard.

**Comment by JJdev95** [comment]
Same issue here game feels like 30 fps even tho i have 110

**Comment by JoelYourstone** [comment]
@jeffhill 

**ETL file** 
https://www.dropbox.com/s/u9jk1zu2xspav8k/2022-06-09_22-54-43_jorel.etl?dl=0

**Screen capture of what you see when the trace was running**
https://www.dropbox.com/s/l1re7o3pjojq2qo/Dota%202%202022-06-09%2022-57-24.mp4?dl=0

I can reproduce this very easily on my machine, I just start a custom lobby, pick snapfire (prolly not relevant), then watch the lane creeps stutter towards the lanes.

If you need any more info about system or so, lmk, I don't know what exists in ETL files :D

**Comment by Enivoke** [comment]
I am unable to play the game currently but I have very similar build.

One time it was lagging for me and I've disabled overwolf Dota plus and Maiafterburner and it was fine for me afterwards. I can't say anything for now.

**Comment by eshin087** [comment]
@jeffhill 

Please see the ETL file of my trace. Thank you as always!

[](https://drive.google.com/file/d/1wjWhqXxent8cjHZyELGIvgId46zH_ptj/view?usp=sharing)

**Comment by xuanwuuu** [comment]
@jeffhill This is the ETL file for my machine.
https://drive.google.com/file/d/1EaITDiYn8PoY9tnw7zZTQOzbi--r6PVL/view?usp=sharing

It only happen when I'm in game. Demo/Private Lobby or Watching game doesn't happen at all. I have to create a private lobby and select a server(cannot be local server), then i can simulate this.

The FPS is running at 144 but will drop drastically and goes back up to 144. But with 144 FPS the game graphic are still stuttering.

**Comment by nikitades** [comment]
Played a bunch of games yesterday, all of them vary from totally unplayable to barely playable. E.g. you can't see Roshan dying due to the packet loss (or what is it?), you only hear the sound. Or you teleport to the outpost and there's no moment of teleport arrival. You just appear nearby.

System:

Mac M1 Max 16"
32 Gb Ram
Mac OS

**Comment by Jewst** [comment]
Same issue, 3/4 of us have this, some games are near unplayable it is so choppy. No issue before this, and no issue with our internet.

**Comment by shubhrathi** [comment]
I have to tell that even recent [update](https://www.reddit.com/r/DotA2/comments/v919b9/dota_2_update_for_late_6922_61022/?utm_medium=android_app&utm_source=share) micro stutter still happens.

**Comment by apollorust** [comment]
I nearly started debugging my system because of this but Reddit randomly showed the bug thread. Still stuttering, just played a game.

**Comment by BenjinZA** [comment]
While I have not encountered this myself, looking at [this](https://www.reddit.com/r/DotA2/comments/v8gmbg/anyone_else_has_mini_stutters_since_last_update/) video on reddit shows that the stuttering is not game wide. Look at the couriers that are idle in the base as Marci is leaving. Both Marci and Night Stalker's courier stutter, but the couriers in base do not.

It's harder to spot but the tower idle up and down bob are also not stuttering while Marci is.

**Comment by Seitei** [comment]
Probably unrelated to this particular issue, but at game start I saw a quite sizeable "banner" made of purple and black checkered squares. Didn't go away until I typed something in the chat.

**Comment by buffakee** [comment]
Match ID: 6610793518

Didn't note of exact moments when it happened, but I remember it happened throughout the game. I did ask my teammates if anyone else is lagging, and they said no. They might have just not noticed, but it also could suggest the stutters were isolated to me alone.

Also my FPS was p consistent on my PC (no abnormal 1% lows), and I had 0 packet loss during the stutters.

I was the windranger in this game.

**Comment by psychoman1** [comment]
![image](https://user-images.githubusercontent.com/56450469/173155641-2fd8a43f-9654-4bef-a335-47159a0a14e6.png)
this is the kinda consol errors I get right when stutters happen.
usually it says unable to load texture/particle/model etc.

**Comment by eshin087** [comment]
@jeffhill 

Hello Mr. Hill. I've played a few games tonight and the games are much better if you've been making changes. 

I wasn't able to play in borderless window before 7.31d (I was experiencing these mini stutters only in borderless window), but now I feel like the stutters aren't happening as much in borderless as well. Will keep on playing. Thank you for all your help!

**Comment by nobling** [comment]
@jeffhill I just tried 1 more game today, and I instantly abandoned it.

180 fps
20 ms latency
0% packet loss
but cant move at all since 7.31d lmao

**Comment by wdttwdtt** [comment]
Here is the match ID: https://www.dotabuff.com/matches/6608743326

This happened throughout the game. I did have a firmware update on my PC which i thought was the issue. But after rebooting my PC, the next games I played were completely fine. I was the Disruptor if it matters

EDIT: my ping was completely fine. But the FPS did hover around from 80-90

**Comment by mk30a** [comment]
hello @jeffhill  will you check this one  try to make lobby with server not local host, enable cheat -wtf then pick pl and buy aghs after that spam his ulti you will notice stutter.

**Comment by Aluerie** [comment]
![image](https://user-images.githubusercontent.com/33165440/173187860-338f88f5-8524-4462-a470-4a301876f05c.png)

is this issue closeable ? does anybody still suffer stutters/lags/etc ?

**Comment by md97x** [comment]
@jeffhill could you please let us know what was the issue? It seems interesting; I even tried debugging the game myself :)

**Comment by shubhrathi** [comment]
@eshin087 You can close this ticket. Issue is fixed. Confirmed by [Jeff](https://www.reddit.com/r/DotA2/comments/v9cpmy/update_on_microstutters/)

**Comment by Seitei** [comment]
I played a game after the fix, no stuttering, thanks for the fix.

Btw, any tl;dr on what caused it if you can disclose? just curious.

**Comment by Misezicedark** [comment]
Right in time for a rainy weekend! Mac M1 Max, no problems anymore. Thank you @jeffhill and the dev team. You guys are the best!

**Comment by apollorust** [comment]
Still stuttering for me sometimes, now it seems to happen after using skills.


> I played a game after the fix, no stuttering, thanks for the fix.
> 
> Btw, any tl;dr on what caused it if you can disclose? just curious.
+1, as a programmer it would be nice to know a few lines about the problem.

**Comment by notanothergithubname** [comment]
Not solved for iMac user here, stuttering is still as bad. Doesn't happen in demo mode, only in live games, spectator if not lobby games. Totally unplayable and getting flamed in game. Not sure how to show video here.

**Comment by Aluerie** [comment]
you can upload `.mp4`/`.mov` file with dragging them to comment typing field or you can upload it on youtube/imgur

**Comment by notanothergithubname** [comment]
https://share.icloud.com/photos/07bkb7_elM4QsRwwsyV_2iD2g

Notice the stuttering on Vulcan driver (iMac) and also the constant mini network spikes for some weird reason that gets progressively worse whenever spells and animations are casted. When spectating, the spikes are just like the video, the actual game itself is way way way worse.

Match ID: 6613139746

I am running on a Asus AX88u network and have been checking my network but there's no problem with it. It was the 7.31d patch that broke my Dota for some reason. Painfully unplayable even with the supposed 'fix', there's been no differences at all.

**Comment by Cronoadvan** [comment]
> [System]
> OS:              Manjaro Linux 21.2.6 Qonos
> Arch:            x86_64
> Kernel:          5.15.41-1-MANJARO
> Desktop:         KDE
> Display Server:  x11
> 
> [CPU]
> Vendor:          AuthenticAMD
> Model:           AMD Ryzen 7 3700X 8-Core Processor
> Physical cores:  8
> Logical cores:   16
> 
> [Memory]
> RAM:             15.6 GB
> Swap:            0.0 GB
> 
> [Graphics]
> Vendor:          AMD
> OpenGL Renderer: AMD Radeon RX 580 Series (polaris10, LLVM 13.0.1, DRM 3.42, 5.15.41-1-MANJARO)
> OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.2.0-devel (git-4896e136b6)
> OpenGL Core:     4.6 (Core Profile) Mesa 22.2.0-devel (git-4896e136b6)
> OpenGL ES:       OpenGL ES 3.2 Mesa 22.2.0-devel (git-4896e136b6)
> Vulkan:          Supported
> 

Stutters have been fixed on my system. Still unable to access Dota TV.

**Comment by deathkiller1** [comment]
Why was this closed without a fix?

**Comment by Aluerie** [comment]
it is fixed - [post](https://www.reddit.com/r/DotA2/comments/v9cpmy/update_on_microstutters/?utm_source=share&utm_medium=web2x&context=3) + [insightful comment](https://www.reddit.com/r/DotA2/comments/v9cpmy/comment/ic1krlu/?utm_source=share&utm_medium=web2x&context=3)

but I can agree, a bit weird that Jeff didnt say anything in here, maybe just in case somebody still has stutters for some other reasons so we can still report it ? 

idk, person above shared match with lag spikes ;

**Comment by deathkiller1** [comment]
Thanks @Aluerie for the info.. I didn't want to risk going into a ranked game earlier.. post-fix i played 2 games, looks to be fine from my end.. Thanks @jeffhill and team for the fix.. also thanks Jeff for the explanation on that reddit thread, i like it when it's detailed since I'm a dev myself

**Comment by notanothergithubname** [comment]
It’s all fixed now, patch works for macOS too. Cheers.

**Comment by notanothergithubname** [comment]
Issue is back again. Thread reopened on:

https://github.com/jeffhill/Dota2/issues/1223

**Comment by lucascarvalho** [comment]
Yes, I still have the same issue. I using Mac OS Intel.
It seems to be related to the network, it get some spikes on the ping out of the blue. It's not my internet because other games works just fine.

**Comment by mouyipen** [comment]
> ![image](https://user-images.githubusercontent.com/56450469/173155641-2fd8a43f-9654-4bef-a335-47159a0a14e6.png) this is the kinda consol errors I get right when stutters happen. usually it says unable to load texture/particle/model etc.

that's cool

**Comment by nurrokhaini** [comment]
I get this issue.
i try to reinstall dota, steam, driver VGA still same.
pls help

**Comment by eddess** [comment]
Still stuttering badly on M1 mac pro 16gb

**Comment by erdemece** [comment]
this is stil happening to a lot of people. in my case I have RTX 3080, AMD 5600x, 32 GB RAM 3600Mhz new installation. windows 11  has all the latest driver updates and windows updates.

**Comment by Seitei** [comment]
Last match was unplayable, seems like the issue is back, well at least for me.

**Comment by Greenelephan** [comment]
+1
I recently bought a mac mini on a m2 chip 8gb and decided to play a couple of matches. It's impossible to play, constantly microshuttering from 20 to 90 ping, although the fps is stable 120. 
Patch 7.32d

**Comment by IgorHoruzha** [comment]
#15078  Possible the same issue. Do You still have the issue?

**Comment by kaisenbaka** [comment]
yeah just ghost it like nothing ever happened, issue already 2 years on still yet not fixed

**Comment by zoomdbz** [comment]
I am having this microstutter issue every 30 secs or so it freezes for 1-10 seconds. No fps drop, no lag spike in ping. Not sure why but the new update caused this issue to happen again. Please fix
